"""Curated fallback evidence for common everyday health questions.

These records are source-traceable snapshots from authoritative public-health or
clinical guidance. They are a fallback when live literature retrieval is
unavailable; they are not synthetic/demo scenarios.
"""
from .evidence_provider import EvidenceRecord


COMMON_HEALTH_RECORDS = [
    EvidenceRecord(
        id="nhs-cuts-grazes-water-2026",
        keywords=("luka", "luka terbuka", "cuts", "grazes", "water", "wound care", "infeksi luka"),
        title="Cuts and grazes",
        source="NHS",
        source_type="government",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.nhs.uk/conditions/cuts-and-grazes/",
        stance="neutral",
        excerpt="NHS advises rinsing cuts with tap or bottled water, drying the surrounding area and keeping the dressing clean and dry. Pus, increasing redness, swelling or pain can be signs of wound infection.",
        quality=0.96,
        authority_level=1,
        authority_score=0.97,
        verified=True,
        demo=False,
        provider="curated-government",
        independent_group="NHS",
        trace_note="NHS wound-care guidance; does not by itself establish that water directly causes pus.",
    ),
    EvidenceRecord(
        id="nhs-wound-infection-2026",
        keywords=("luka", "wound", "nanah", "pus", "bernanah", "infeksi", "infection", "wet", "dry"),
        title="Patient Self Care — Wound Dressing",
        source="North Tees and Hartlepool NHS Foundation Trust",
        source_type="government",
        publication_date="2026-08-24",
        retrieved_at="2026-09-27",
        url="https://www.nth.nhs.uk/resources/patient-self-care-wound-dressing/",
        stance="neutral",
        excerpt="The guidance advises keeping skin around a wound dry and monitoring for infection signs including increased wetness, offensive smell and yellow or green pus.",
        quality=0.94,
        authority_level=1,
        authority_score=0.94,
        verified=True,
        demo=False,
        provider="curated-government",
        independent_group="North Tees NHS Foundation Trust",
        trace_note="NHS Foundation Trust wound-care guidance; pus is described as a sign of infection rather than proof that water caused it.",
    ),
    EvidenceRecord(
        id="uclh-wound-care-2026",
        keywords=("luka", "wound", "nanah", "pus", "bernanah", "infeksi", "infection", "basah", "moist"),
        title="Wound care",
        source="University College London Hospitals NHS Foundation Trust",
        source_type="government",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.uclh.nhs.uk/patients-and-visitors/patient-information-pages/wound-care",
        stance="neutral",
        excerpt="UCLH advises keeping an operation site clean and dry in the early healing period and lists redness, swelling, heat and blood or pus as possible signs of infection.",
        quality=0.94,
        authority_level=1,
        authority_score=0.94,
        verified=True,
        demo=False,
        provider="curated-government",
        independent_group="UCLH",
        trace_note="Hospital wound-care guidance; relevant context for wound moisture and infection signs.",
    ),
    EvidenceRecord(
        id="aad-acne-diet-2026",
        keywords=("jerawat", "acne", "gula", "manis", "makanan manis", "minuman manis", "high glycemic", "diet"),
        title="Can the right diet get rid of acne?",
        source="American Academy of Dermatology",
        source_type="professional_medical_org",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.aad.org/public/diseases/acne/causes/diet",
        stance="support",
        excerpt="The American Academy of Dermatology notes that small studies suggest a low-glycemic diet may reduce acne, while more research is needed and not every study finds the same connection.",
        quality=0.91,
        authority_level=2,
        authority_score=0.91,
        verified=True,
        demo=False,
        provider="curated-medical-guidance",
        independent_group="AAD",
        trace_note="Dermatology guidance with explicit uncertainty about diet-acne evidence.",
    ),
    EvidenceRecord(
        id="cdc-short-sleep-obesity-2026",
        keywords=("kurang tidur", "tidur kurang", "sleep deprivation", "short sleep", "tidur", "obesitas", "obesity", "berat badan"),
        title="Short Sleep Duration and Sleep Difficulties Among Adults: United States, 2024",
        source="U.S. Centers for Disease Control and Prevention",
        source_type="government",
        publication_date="2026-04-01",
        retrieved_at="2026-09-27",
        url="https://www.cdc.gov/nchs/products/databriefs/db559.htm",
        stance="support",
        excerpt="CDC notes that poor sleep health, including insufficient sleep, has been linked to detrimental health conditions including obesity and depression.",
        quality=0.95,
        authority_level=1,
        authority_score=0.97,
        verified=True,
        demo=False,
        provider="curated-government",
        independent_group="CDC",
        trace_note="CDC National Center for Health Statistics data brief; association rather than proof of simple one-way causation.",
    ),
    EvidenceRecord(
        id="who-physical-activity-2024",
        keywords=("olahraga", "aktivitas fisik", "physical activity", "exercise", "diabetes", "jantung", "stroke", "berat badan", "obesitas"),
        title="Physical activity",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2024-06-26",
        retrieved_at="2026-09-27",
        url="https://www.who.int/news-room/fact-sheets/detail/physical-activity",
        stance="support",
        excerpt="WHO states that regular physical activity helps prevent and manage cardiovascular disease, cancer and diabetes and is associated with better health and body-fat measures.",
        quality=0.97,
        authority_level=1,
        authority_score=0.98,
        verified=True,
        demo=False,
        provider="curated-international-agency",
        independent_group="WHO",
        trace_note="WHO official fact sheet on physical activity and health outcomes.",
    ),
    EvidenceRecord(
        id="cdc-wash-raw-chicken-2026",
        keywords=("ayam", "ayam mentah", "cuci ayam", "mencuci ayam", "raw chicken", "food poisoning", "keracunan makanan"),
        title="Preventing Food Poisoning",
        source="U.S. Centers for Disease Control and Prevention",
        source_type="government",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.cdc.gov/food-safety/prevention/",
        stance="contradict",
        excerpt="CDC says raw chicken is ready to cook and does not need to be washed first because washing can spread germs to other foods, the sink and counters.",
        quality=0.97,
        authority_level=1,
        authority_score=0.98,
        verified=True,
        demo=False,
        provider="curated-government",
        independent_group="CDC",
        trace_note="CDC food-safety guidance.",
    ),
    EvidenceRecord(
        id="nhs-nosebleed-forward-2026",
        keywords=("mimisan", "hidung berdarah", "nosebleed", "epistaxis", "menengadah", "condong"),
        title="Nosebleed",
        source="NHS",
        source_type="government",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.nhs.uk/conditions/nosebleed/",
        stance="contradict",
        excerpt="NHS advises sitting down and leaning forward during a nosebleed rather than tilting the head back.",
        quality=0.96,
        authority_level=1,
        authority_score=0.97,
        verified=True,
        demo=False,
        provider="curated-government",
        independent_group="NHS",
        trace_note="NHS first-aid guidance for nosebleeds.",
    ),
    EvidenceRecord(
        id="nhs-hiccups-2026",
        keywords=("cegukan", "hiccups", "air dingin", "cold water", "air", "menahan napas"),
        title="Hiccups",
        source="NHS",
        source_type="government",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.nhs.uk/symptoms/hiccups/",
        stance="neutral",
        excerpt="NHS lists sipping ice-cold water and several other self-care methods that some people find helpful for hiccups, while noting there is no evidence they work for everyone.",
        quality=0.95,
        authority_level=1,
        authority_score=0.96,
        verified=True,
        demo=False,
        provider="curated-government",
        independent_group="NHS",
        trace_note="NHS symptom guidance with explicit uncertainty about self-care methods.",
    ),
    EvidenceRecord(
        id="nhs-burns-cool-water-2026",
        keywords=("luka bakar", "terbakar", "burn", "scald", "air mengalir", "cool running water"),
        title="Burns and scalds",
        source="NHS",
        source_type="government",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.nhs.uk/conditions/burns-and-scalds/",
        stance="support",
        excerpt="NHS advises holding a burn or scald under cool running water for 20 minutes as soon as possible.",
        quality=0.96,
        authority_level=1,
        authority_score=0.97,
        verified=True,
        demo=False,
        provider="curated-government",
        independent_group="NHS",
        trace_note="NHS first-aid guidance for burns and scalds.",
    ),
    EvidenceRecord(
        id="niddk-lactose-intolerance-2026",
        keywords=("susu", "milk", "laktosa", "lactose", "diare", "kembung", "gas", "mual", "intoleransi laktosa"),
        title="Symptoms & Causes of Lactose Intolerance",
        source="National Institute of Diabetes and Digestive and Kidney Diseases",
        source_type="government",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.niddk.nih.gov/health-information/digestive-diseases/lactose-intolerance/symptoms-causes",
        stance="support",
        excerpt="NIDDK states that people with lactose intolerance can develop bloating, diarrhea, gas, nausea and abdominal pain within hours after consuming milk or lactose-containing foods.",
        quality=0.96,
        authority_level=1,
        authority_score=0.98,
        verified=True,
        demo=False,
        provider="curated-government",
        independent_group="NIDDK",
        trace_note="NIH/NIDDK patient and professional health information.",
    ),
]
