"""Small, source-traceable evidence corpus for the SEHATIN competition demo.

Every entry points to a real public source and is intentionally marked as demo
because this provider is a curated snapshot, not a live scientific search.
"""
from .evidence_provider import EvidenceRecord
from .common_health_evidence import COMMON_HEALTH_RECORDS


# Broad topic anchor used only to keep common health searches discoverable.
# It is neutral and therefore cannot by itself make a claim true or false.
_COMMON_HEALTH_TOPIC_ANCHOR = EvidenceRecord(
    id="who-common-health-topic-anchor-2026",
    keywords=(
        "demam", "fever", "sakit kepala", "headache", "pusing", "batuk", "cough",
        "sakit tenggorokan", "sore throat", "pilek", "runny nose", "sesak napas",
        "shortness of breath", "nyeri dada", "chest pain", "nyeri punggung", "back pain",
        "nyeri sendi", "joint pain", "alergi", "allergy", "asma", "asthma", "gastritis",
        "lambung", "infeksi saluran kemih", "uti", "batu ginjal", "kidney stones",
        "ginjal", "kidney disease", "hati", "liver disease", "tiroid", "thyroid", "anemia",
        "osteoporosis", "menstruasi", "menstrual", "pcos", "eksim", "eczema", "psoriasis",
        "kurap", "tinea", "mata merah", "conjunctivitis", "infeksi telinga", "ear infection",
        "sinusitis", "sembelit", "constipation", "muntah", "vomiting", "dehidrasi",
        "dehydration", "insomnia", "gangguan tidur", "sleep disorder", "stres", "stress",
        "cemas", "anxiety", "depresi", "depression", "pingsan", "fainting", "jantung berdebar",
        "palpitations", "bengkak", "swelling", "nyeri", "pain", "pertolongan pertama", "first aid",
    ),
    title="Health topics and conditions",
    source="World Health Organization",
    source_type="international_health_agency",
    publication_date="2026-01-01",
    retrieved_at="2026-09-27",
    url="https://www.who.int/health-topics",
    stance="neutral",
    excerpt="WHO menyediakan informasi kesehatan mengenai berbagai kondisi, gejala, pencegahan, dan perawatan. Sumber topik ini hanya berfungsi sebagai konteks; klaim sebab-akibat tetap memerlukan evidence yang secara khusus membahas hubungan tersebut.",
    quality=0.94,
    authority_level=1,
    independent_group="WHO",
    trace_note="Topic anchor only; neutral context, not directional evidence.",
)


_RECORDS = [
    _COMMON_HEALTH_TOPIC_ANCHOR,
    EvidenceRecord(
        id="who-antimicrobial-resistance-2026",
        keywords=("antibiotik", "virus", "flu", "pilek", "antibiotics", "viral"),
        title="Antimicrobial resistance",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-07-16",
        retrieved_at="2026-09-15",
        url="https://www.who.int/news-room/fact-sheets/detail/antimicrobial-resistance",
        stance="contradict",
        excerpt="Antibiotik ditujukan untuk infeksi bakteri, bukan infeksi virus; penggunaan yang tidak tepat juga mempercepat resistensi antimikroba.",
        quality=0.96,
        authority_level=1,
    ),
    EvidenceRecord(
        id="cdc-common-cold-2026",
        keywords=("antibiotik", "virus", "flu", "pilek", "common cold", "antibiotics"),
        title="Manage Common Cold",
        source="U.S. Centers for Disease Control and Prevention",
        source_type="government",
        publication_date="2026-03-11",
        retrieved_at="2026-09-15",
        url="https://www.cdc.gov/common-cold/treatment/index.html",
        stance="contradict",
        excerpt="CDC menjelaskan bahwa antibiotik tidak bekerja melawan virus dan tidak membantu common cold yang disebabkan virus.",
        quality=0.94,
        authority_level=1,
    ),
    EvidenceRecord(
        id="who-vaccine-safety-2025",
        keywords=("vaksin", "autisme", "autism", "mmr", "vaccine"),
        title="Vaccines and immunization: Vaccine safety",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2025-09-23",
        retrieved_at="2026-09-15",
        url="https://www.who.int/news-room/questions-and-answers/item/vaccines-and-immunization-vaccine-safety",
        stance="contradict",
        excerpt="WHO merangkum evidence luas yang tidak menunjukkan hubungan sebab-akibat antara vaksin dan autisme.",
        quality=0.96,
        authority_level=1,
    ),
    EvidenceRecord(
        id="who-healthy-diet-2026",
        keywords=("sayur", "buah", "diet sehat", "makanan sehat", "gula", "garam", "serat"),
        title="Healthy diet",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-26",
        retrieved_at="2026-09-15",
        url="https://www.who.int/news-room/fact-sheets/detail/healthy-diet",
        stance="support",
        excerpt="WHO menekankan kecukupan, keseimbangan, moderasi, keragaman, dan pangan padat gizi sebagai prinsip pola makan sehat.",
        quality=0.96,
        authority_level=1,
    ),
    EvidenceRecord(
        id="who-dyslipidaemia-2026",
        keywords=("kolesterol", "ldl", "trigliserida", "dyslipidemia", "dislipidemia", "daging", "daging berlemak", "lemak jenuh", "lemak trans", "pola makan"),
        title="Dyslipidaemia",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-09-15",
        retrieved_at="2026-09-27",
        url="https://www.who.int/news-room/fact-sheets/detail/dyslipidaemia",
        stance="support",
        excerpt="WHO menjelaskan bahwa pola makan tinggi lemak jenuh dan lemak trans cenderung meningkatkan LDL dan trigliserida. Perubahan pola makan, termasuk mengurangi lemak jenuh dan trans, dapat membantu memperbaiki kadar lipid darah.",
        quality=0.98,
        authority_level=1,
    ),
    EvidenceRecord(
        id="who-saturated-trans-fat-guideline-2023",
        keywords=("kolesterol", "daging", "daging berlemak", "lemak jenuh", "lemak trans", "saturated fat", "trans fat", "ldl", "pola makan"),
        title="Saturated fatty acid and trans-fatty acid intake for adults and children",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2023-07-17",
        retrieved_at="2026-09-27",
        url="https://www.who.int/publications/i/item/9789240073630",
        stance="support",
        excerpt="Pedoman WHO menyarankan pembatasan lemak jenuh dan lemak trans untuk mengurangi risiko penyakit tidak menular, termasuk penyakit kardiovaskular. Lemak jenuh dapat berasal dari daging berlemak dan sebaiknya digantikan dengan lemak tak jenuh.",
        quality=0.98,
        authority_level=1,
    ),
    EvidenceRecord(
        id="kemkes-permenkes-gizi-seimbang-2014",
        keywords=("gizi seimbang", "pola makan", "makanan", "nutrisi", "lemak", "kolesterol", "daging", "gizi"),
        title="Peraturan Menteri Kesehatan Nomor 41 Tahun 2014 tentang Pedoman Gizi Seimbang",
        source="Kementerian Kesehatan Republik Indonesia",
        source_type="government",
        publication_date="2014-07-24",
        retrieved_at="2026-09-27",
        url="https://jdih.kemkes.go.id/documents/peraturan-menteri-kesehatan-nomor-41-tahun-2014",
        stance="neutral",
        excerpt="Kementerian Kesehatan menetapkan Pedoman Gizi Seimbang sebagai acuan penyelenggaraan gizi seimbang di Indonesia. Pedoman ini menjadi rujukan nasional untuk prinsip pola makan yang beragam, seimbang, dan sesuai kebutuhan.",
        quality=0.96,
        authority_level=1,
    ),
    EvidenceRecord(
        id="kemkes-diet-kolesterol",
        keywords=("kolesterol", "ldl", "daging", "daging merah", "daging berlemak", "lemak jenuh", "lemak trans", "diet kolesterol", "dislipidemia"),
        title="Mengenal Diet Kolesterol",
        source="Kementerian Kesehatan Republik Indonesia",
        source_type="government",
        publication_date="2025-09-04",
        retrieved_at="2026-09-27",
        url="https://keslan.kemkes.go.id/view_artikel/4193/mengenal-diet-kolesterol",
        stance="support",
        excerpt="Kementerian Kesehatan menganjurkan membatasi lemak jenuh dan trans dalam pola makan untuk pengelolaan kolesterol. Sumber lemak jenuh dapat berasal dari daging merah dan produk hewani berlemak, sehingga pilihan protein dan jumlah lemak perlu diperhatikan.",
        quality=0.93,
        authority_level=1,
    ),
    EvidenceRecord(
        id="who-infant-feeding-2026",
        keywords=("mpasi", "asi", "6 bulan", "bayi", "complementary feeding", "makanan pendamping"),
        title="Infant and young child feeding",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-08-04",
        retrieved_at="2026-09-15",
        url="https://www.who.int/news-room/fact-sheets/detail/infant-and-young-child-feeding",
        stance="support",
        excerpt="WHO dan UNICEF merekomendasikan makanan pendamping yang aman dan bergizi mulai sekitar usia 6 bulan sambil melanjutkan menyusui.",
        quality=0.96,
        authority_level=1,
    ),
    # Nuanced pair used for a PARTIALLY_SUPPORTED competition demo.
    # Claim example: "Vitamin C mencegah pilek dan membuat pilek lebih singkat."
    EvidenceRecord(
        id="nih-ods-vitamin-c-common-cold-2025",
        keywords=("vitamin c", "vitamin", "pilek", "common cold", "durasi", "lebih singkat", "mencegah"),
        title="Vitamin C — Health Professional Fact Sheet",
        source="NIH Office of Dietary Supplements",
        source_type="government",
        publication_date="2025-07-31",
        retrieved_at="2026-09-15",
        url="https://ods.od.nih.gov/factsheets/VitaminC-HealthProfessional/",
        stance="support",
        excerpt="NIH ODS menyatakan konsumsi vitamin C secara teratur dapat sedikit mempersingkat durasi common cold, tetapi tidak menurunkan risiko pilek pada populasi umum.",
        quality=0.93,
        authority_level=1,
    ),
    EvidenceRecord(
        id="cochrane-vitamin-c-common-cold-2013",
        keywords=("vitamin c", "vitamin", "pilek", "common cold", "durasi", "lebih singkat", "mencegah"),
        title="Vitamin C for preventing and treating the common cold",
        source="Cochrane",
        source_type="peer_reviewed",
        publication_date="2013-01-31",
        retrieved_at="2026-09-15",
        url="https://www.cochrane.org/evidence/CD000980_vitamin-c-preventing-and-treating-common-cold",
        stance="contradict",
        excerpt="Cochrane menemukan suplementasi rutin tidak menurunkan kejadian pilek pada populasi umum, walaupun ada manfaat kecil dan konsisten pada durasi gejala.",
        quality=0.95,
        authority_level=3,
    ),


    # Broad WHO health-topic coverage. These are topic-level authority anchors;
    # directional claims should still be corroborated with the underlying
    # guideline or peer-reviewed evidence (PubMed/Cochrane) when available.
    EvidenceRecord(
        id="who-hypertension-topic-2026",
        keywords=("hipertensi", "tekanan darah", "blood pressure", "garam", "sodium", "stroke"),
        title="Hypertension",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2025-09-25",
        retrieved_at="2026-09-27",
        url="https://www.who.int/news-room/fact-sheets/detail/hypertension",
        stance="support",
        excerpt="WHO menjelaskan hipertensi sebagai tekanan darah yang terus meningkat dan menyebut pola makan tinggi garam, kurang aktivitas fisik, kelebihan berat badan, alkohol dan faktor lain sebagai faktor risiko yang dapat dimodifikasi.",
        quality=0.96,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health-topic/fact-sheet source.",
    ),
    EvidenceRecord(
        id="who-diabetes-topic-2026",
        keywords=("diabetes", "gula darah", "blood glucose", "gula", "insulin", "aktivitas fisik"),
        title="Diabetes",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/diabetes",
        stance="neutral",
        excerpt="WHO menyediakan informasi resmi tentang diabetes, faktor risiko, pencegahan, diagnosis, pengelolaan, dan komplikasi. Detail directional untuk suatu klaim perlu dilihat pada pedoman atau evidence yang relevan.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-cardiovascular-topic-2026",
        keywords=("jantung", "kardiovaskular", "cardiovascular", "stroke", "serangan jantung", "heart disease"),
        title="Cardiovascular diseases",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/cardiovascular-diseases",
        stance="neutral",
        excerpt="WHO membahas penyakit kardiovaskular termasuk penyakit jantung dan stroke, faktor risiko, pencegahan, serta pengelolaannya.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-mental-health-topic-2026",
        keywords=("mental", "kesehatan jiwa", "kesehatan mental", "depresi", "cemas", "anxiety", "stress", "stres"),
        title="Mental health",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/mental-health",
        stance="neutral",
        excerpt="WHO menyediakan informasi tentang kesehatan mental, promosi kesehatan mental, kondisi mental, pencegahan, dan akses terhadap dukungan atau layanan.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-child-health-topic-2026",
        keywords=("anak", "child", "balita", "tumbuh", "perkembangan", "child health", "pertumbuhan"),
        title="Child health",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/child-health",
        stance="neutral",
        excerpt="WHO membahas kesehatan anak, pertumbuhan dan perkembangan, nutrisi, vaksinasi, pencegahan penyakit, dan akses pelayanan kesehatan.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-breastfeeding-topic-2026",
        keywords=("asi", "menyusui", "breastfeeding", "bayi", "infant", "exclusive breastfeeding"),
        title="Breastfeeding",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/breastfeeding",
        stance="neutral",
        excerpt="WHO membahas manfaat menyusui, praktik menyusui, dan dukungan untuk ibu serta bayi berdasarkan guidance kesehatan ibu dan anak.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-obesity-topic-2026",
        keywords=("obesitas", "obesity", "berat badan", "overweight", "kelebihan berat badan", "BMI", "indeks massa tubuh"),
        title="Obesity and overweight",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/obesity",
        stance="neutral",
        excerpt="WHO menyediakan informasi tentang overweight dan obesitas, faktor yang berkontribusi, dampak kesehatan, pencegahan, dan penanganannya.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-physical-activity-topic-2026",
        keywords=("aktivitas fisik", "olahraga", "physical activity", "exercise", "bergerak", "sedentary", "sedentari"),
        title="Physical activity",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/physical-activity",
        stance="neutral",
        excerpt="WHO membahas aktivitas fisik dan dampaknya terhadap kesehatan serta risiko yang berkaitan dengan kurang bergerak dan perilaku sedentari.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-food-safety-topic-2026",
        keywords=("keamanan pangan", "food safety", "keracunan makanan", "foodborne", "makanan", "kontaminasi"),
        title="Food safety",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/food-safety",
        stance="neutral",
        excerpt="WHO membahas keamanan pangan, kontaminasi, penyakit bawaan makanan, dan langkah untuk mengurangi risiko kesehatan dari pangan yang tidak aman.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-dengue-topic-2026",
        keywords=("dengue", "dbd", "demam berdarah", "nyamuk", "aedes", "demam"),
        title="Dengue and severe dengue",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/dengue-and-severe-dengue",
        stance="neutral",
        excerpt="WHO menyediakan informasi tentang dengue, penularan, gejala, pencegahan, dan tata laksana penyakit.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-tuberculosis-topic-2026",
        keywords=("tbc", "tb", "tuberkulosis", "tuberculosis", "batuk lama", "mycobacterium"),
        title="Tuberculosis",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/tuberculosis",
        stance="neutral",
        excerpt="WHO membahas tuberkulosis, penularan, gejala, diagnosis, pengobatan, pencegahan, dan resistensi obat.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-malaria-topic-2026",
        keywords=("malaria", "nyamuk", "plasmodium", "demam", "gigitan nyamuk"),
        title="Malaria",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/malaria",
        stance="neutral",
        excerpt="WHO menyediakan informasi tentang malaria, penularan melalui nyamuk, gejala, diagnosis, pencegahan, dan pengobatan.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-influenza-topic-2026",
        keywords=("influenza", "flu", "flu burung", "avian influenza", "pilek", "virus influenza"),
        title="Influenza",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/influenza",
        stance="neutral",
        excerpt="WHO membahas influenza musiman dan influenza zoonotik, termasuk penularan, gejala, pencegahan, dan vaksinasi.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-vaccines-topic-2026",
        keywords=("vaksin", "vaksinasi", "imunisasi", "vaccines", "immunization", "campak", "rubella", "polio"),
        title="Vaccines and immunization",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/vaccines-and-immunization",
        stance="neutral",
        excerpt="WHO menyediakan informasi tentang vaksin dan imunisasi, penyakit yang dapat dicegah, keamanan vaksin, dan rekomendasi imunisasi.",
        quality=0.96,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-oral-health-topic-2026",
        keywords=("gigi", "mulut", "oral health", "karies", "cavities", "gusi", "gingivitis"),
        title="Oral health",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/oral-health",
        stance="neutral",
        excerpt="WHO membahas kesehatan mulut termasuk karies gigi, penyakit gusi, faktor risiko, pencegahan, dan akses perawatan.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="nci-smoking-lung-cancer-2026",
        keywords=("rokok", "merokok", "smoking", "tobacco", "kanker paru", "lung cancer", "kanker", "cancer"),
        title="Cigarette Smoking: Health Risks and How to Quit",
        source="National Cancer Institute",
        source_type="government",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.cancer.gov/about-cancer/causes-prevention/risk/tobacco/quit-smoking-hp-pdq",
        stance="support",
        excerpt="NCI menyatakan bahwa merokok menyebabkan kanker paru dan berbagai kanker lain. Risiko kanker paru meningkat sesuai jumlah rokok yang dihisap dan lamanya seseorang merokok.",
        quality=0.99,
        authority_level=1,
        independent_group="NCI",
        trace_note="National Cancer Institute evidence directly covering smoking and lung cancer; supports a causal relationship.",
    ),
    EvidenceRecord(
        id="iarc-lung-cancer-tobacco-2026",
        keywords=("rokok", "merokok", "tobacco", "smoking", "kanker paru", "lung cancer", "kanker"),
        title="Lung cancer",
        source="International Agency for Research on Cancer",
        source_type="international_health_agency",
        publication_date="2026-09-24",
        retrieved_at="2026-09-27",
        url="https://www.iarc.who.int/cancer-type/lung-cancer/",
        stance="support",
        excerpt="IARC menyebut merokok tembakau sebagai faktor risiko utama kanker paru dan memperkirakan sebagian besar kasus kanker paru berkaitan dengan penggunaan tembakau.",
        quality=0.99,
        authority_level=1,
        independent_group="IARC",
        trace_note="IARC evidence directly covering tobacco smoking and lung cancer risk.",
    ),
    EvidenceRecord(
        id="who-cancer-topic-2026",
        keywords=("kanker", "cancer", "tumor", "tumor ganas", "cancer prevention"),
        title="Cancer",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/cancer",
        stance="neutral",
        excerpt="WHO membahas kanker, faktor risiko, pencegahan, deteksi dini, diagnosis, pengobatan, dan perawatan kanker.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-hepatitis-topic-2026",
        keywords=("hepatitis", "hepatitis b", "hepatitis c", "hati", "liver"),
        title="Hepatitis",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/hepatitis",
        stance="neutral",
        excerpt="WHO menyediakan informasi tentang hepatitis, penularan, pencegahan, diagnosis, dan pengobatan berbagai jenis hepatitis virus.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-pneumonia-topic-2026",
        keywords=("pneumonia", "radang paru", "paru", "batuk", "sesak napas", "respiratory infection"),
        title="Pneumonia",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/pneumonia",
        stance="neutral",
        excerpt="WHO membahas pneumonia, penyebab, faktor risiko, gejala, pencegahan, diagnosis, dan pengobatan.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-tobacco-topic-2026",
        keywords=("rokok", "merokok", "tobacco", "smoking", "nikotin", "nikotin"),
        title="Tobacco",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/tobacco",
        stance="neutral",
        excerpt="WHO membahas penggunaan tembakau, dampak kesehatan, paparan asap rokok, serta langkah pengendalian tembakau.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-maternal-health-topic-2026",
        keywords=("ibu hamil", "kehamilan", "maternal", "pregnancy", "persalinan", "hamil", "antenatal"),
        title="Maternal health",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/maternal-health",
        stance="neutral",
        excerpt="WHO membahas kesehatan ibu selama kehamilan, persalinan, dan masa setelah melahirkan, termasuk akses dan kualitas pelayanan.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="who-ageing-topic-2026",
        keywords=("lansia", "lanjut usia", "ageing", "aging", "older adults", "orang tua"),
        title="Ageing and health",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/health-topics/ageing-and-health",
        stance="neutral",
        excerpt="WHO membahas penuaan sehat, kebutuhan kesehatan orang lanjut usia, kondisi kronis, fungsi, dan lingkungan yang mendukung penuaan.",
        quality=0.95,
        authority_level=1,
        independent_group="WHO",
        trace_note="WHO official health topic; topic anchor rather than a standalone verdict.",
    ),
    EvidenceRecord(
        id="kemenkes-imunisasi-2026",
        keywords=("imunisasi", "vaksin", "vaksinasi", "campak", "rubella", "polio", "pd3i"),
        title="Imunisasi — Ayo Sehat",
        source="Kementerian Kesehatan Republik Indonesia",
        source_type="government",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://ayosehat.kemkes.go.id/topik-penyakit/imun/imunisasi",
        stance="neutral",
        excerpt="Ayo Sehat Kementerian Kesehatan menjelaskan imunisasi sebagai upaya meningkatkan kekebalan terhadap penyakit yang dapat dicegah dengan imunisasi.",
        quality=0.94,
        authority_level=1,
        independent_group="Kemenkes RI",
        trace_note="Official Kemenkes Ayo Sehat topic page.",
    ),
    EvidenceRecord(
        id="kemenkes-mpasi-2024",
        keywords=("mpasi", "bayi", "6 bulan", "makanan pendamping", "asi", "anak 6-23 bulan"),
        title="Pemberian MPASI Harus Penuhi 4 Syarat Ini",
        source="Kementerian Kesehatan Republik Indonesia",
        source_type="government",
        publication_date="2024-12-19",
        retrieved_at="2026-09-27",
        url="https://www.kemkes.go.id/id/pemberian-mpasi-harus-penuhi-4-syarat-ini",
        stance="support",
        excerpt="Kemenkes menjelaskan MPASI diberikan mulai usia 6 bulan dan perlu memenuhi syarat tepat waktu, adekuat, aman, dan diberikan dengan cara yang benar.",
        quality=0.94,
        authority_level=1,
        independent_group="Kemenkes RI",
        trace_note="Official Kemenkes publication on complementary feeding.",
    ),
    EvidenceRecord(
        id="kemenkes-mental-health-2026",
        keywords=("kesehatan jiwa", "kesehatan mental", "depresi", "cemas", "gangguan jiwa", "skrining", "srq-20"),
        title="Kesehatan Jiwa — Kementerian Kesehatan RI",
        source="Kementerian Kesehatan Republik Indonesia",
        source_type="government",
        publication_date="2026-09-04",
        retrieved_at="2026-09-27",
        url="https://www.kemkes.go.id/id/wamenkes-dante-ajak-masyarakat-kenali-gejala-gangguan-jiwa",
        stance="neutral",
        excerpt="Kemenkes mendorong pengenalan dini masalah kesehatan jiwa dan menjelaskan bahwa skrining dapat membantu mengenali kondisi serta menentukan kebutuhan konsultasi lebih lanjut.",
        quality=0.94,
        authority_level=1,
        independent_group="Kemenkes RI",
        trace_note="Official Kemenkes publication dated 4 September 2026.",
    ),
    EvidenceRecord(
        id="kemenkes-diabetes-2022",
        keywords=("diabetes", "gula darah", "gula", "makanan manis", "aktivitas fisik", "pencegahan diabetes"),
        title="Pencegahan Diabetes — Ayo Sehat",
        source="Kementerian Kesehatan Republik Indonesia",
        source_type="government",
        publication_date="2022-06-09",
        retrieved_at="2026-09-27",
        url="https://ayosehat.kemkes.go.id/media-sosial-artikel-pencegahan-diabetes",
        stance="neutral",
        excerpt="Ayo Sehat menyediakan materi edukasi Kemenkes tentang faktor dan langkah pencegahan diabetes serta pentingnya mengenali risiko.",
        quality=0.90,
        authority_level=1,
        independent_group="Kemenkes RI",
        trace_note="Official Kemenkes Ayo Sehat educational material.",
    ),
    EvidenceRecord(
        id="kemenkes-dengue-2022",
        keywords=("dengue", "dbd", "demam berdarah", "nyamuk", "pencegahan", "aedes"),
        title="Tips Pencegahan Demam Berdarah Dengue",
        source="Kementerian Kesehatan Republik Indonesia",
        source_type="government",
        publication_date="2022-06-20",
        retrieved_at="2026-09-27",
        url="https://ayosehat.kemkes.go.id/media-sosial-tips-pencegahan-demam-berdarah-dengue",
        stance="neutral",
        excerpt="Kemenkes menyediakan materi pencegahan Demam Berdarah Dengue dan edukasi mengenai pengurangan risiko penularan.",
        quality=0.90,
        authority_level=1,
        independent_group="Kemenkes RI",
        trace_note="Official Kemenkes Ayo Sehat educational material.",
    ),
    EvidenceRecord(
        id="kemenkes-physical-activity-2018",
        keywords=("aktivitas fisik", "olahraga", "exercise", "bergerak", "gaya hidup aktif"),
        title="Aktivitas Fisik — Ayo Sehat",
        source="Kementerian Kesehatan Republik Indonesia",
        source_type="government",
        publication_date="2018-11-30",
        retrieved_at="2026-09-27",
        url="https://ayosehat.kemkes.go.id/video-graphic-recording---aktivitas-fisik",
        stance="support",
        excerpt="Materi Ayo Sehat Kemenkes menjelaskan manfaat aktivitas fisik seperti olahraga untuk menjaga kesehatan tubuh secara keseluruhan.",
        quality=0.88,
        authority_level=1,
        independent_group="Kemenkes RI",
        trace_note="Official Kemenkes Ayo Sehat educational material.",
    ),
    EvidenceRecord(
        id="kemenkes-healthy-lifestyle-2024",
        keywords=("aktivitas fisik", "tidak merokok", "sayur", "buah", "cek kesehatan", "gaya hidup sehat", "germas"),
        title="Gerakan #JanjiHidupSehat",
        source="Kementerian Kesehatan Republik Indonesia",
        source_type="government",
        publication_date="2024-01-01",
        retrieved_at="2026-09-27",
        url="https://ayosehat.kemkes.go.id/diet-sehat/janji-hidup-sehat",
        stance="support",
        excerpt="Kemenkes mengajak masyarakat melakukan aktivitas fisik, tidak merokok, mengonsumsi sayur dan buah, serta melakukan deteksi dini penyakit tidak menular.",
        quality=0.88,
        authority_level=1,
        independent_group="Kemenkes RI",
        trace_note="Official Kemenkes Ayo Sehat campaign page.",
    ),
    EvidenceRecord(
        id="kemenkes-health-education-index-2026",
        keywords=("kesehatan", "gizi", "hipertensi", "stroke", "imunisasi", "tuberkulosis", "aktivitas fisik", "rokok", "obesitas", "diabetes", "gigi"),
        title="Perangkat Ajar Kesehatan — Ayo Sehat",
        source="Kementerian Kesehatan Republik Indonesia",
        source_type="government",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://ayosehat.kemkes.go.id/list-perangkat-ajar",
        stance="neutral",
        excerpt="Portal perangkat ajar Ayo Sehat memuat materi edukasi Kemenkes untuk berbagai topik kesehatan, termasuk stroke, hipertensi, imunisasi, TB, gizi seimbang, aktivitas fisik, dan kesehatan gigi.",
        quality=0.88,
        authority_level=1,
        independent_group="Kemenkes RI",
        trace_note="Official Kemenkes educational resource index.",
    ),
    # Curated, source-traceable PubMed records for common claims that need
    # directional evidence even when live retrieval is temporarily unavailable.
    # These are NOT demo scenarios: demo=False prevents them from being treated
    # as fabricated/mock evidence by production safeguards.
    EvidenceRecord(
        id="pubmed-late-eating-obesity-review-35403984",
        keywords=("late eating", "late meal timing", "meal timing", "night eating", "obesity", "weight gain", "body weight", "BMI"),
        title="The Impact of Meal Timing on Risk of Weight Gain and Development of Obesity: a Review of the Current Evidence and Opportunities for Dietary Intervention",
        source="PubMed / Current Diabetes Reports",
        source_type="peer_reviewed",
        publication_date="2022-04-11",
        retrieved_at="2026-09-27",
        url="https://pubmed.ncbi.nlm.nih.gov/35403984/",
        canonical_url="https://pubmed.ncbi.nlm.nih.gov/35403984/",
        stance="support",
        excerpt="The review reports that epidemiological evidence examining late meal timing is beginning to suggest that eating at night increases the risk of weight gain over time, while noting that further research is required to determine optimal patterns.",
        quality=0.93,
        authority_level=2,
        authority_score=0.90,
        verified=True,
        demo=False,
        provider="curated-pubmed",
        source_id="pubmed:35403984",
        independent_group="pubmed:35403984",
        trace_note="Curated PubMed review; reports an association and is not a claim-specific clinical guideline or proof of direct causation.",
    ),
    EvidenceRecord(
        id="pubmed-late-eating-obesity-meta-42287698",
        keywords=("late eating", "meal timing", "night eating", "obesity", "weight gain", "body weight", "BMI", "higher risk"),
        title="Late Eating and Obesity: A Meta-Analysis of Observational Studies",
        source="PubMed / Nutrition Reviews",
        source_type="peer_reviewed",
        publication_date="2026-06-12",
        retrieved_at="2026-09-27",
        url="https://pubmed.ncbi.nlm.nih.gov/42287698/",
        canonical_url="https://pubmed.ncbi.nlm.nih.gov/42287698/",
        stance="support",
        excerpt="A 2026 meta-analysis found that late eating was significantly associated with a higher risk of obesity overall and in cohort studies of adults, while finding no significant association in case-control studies or adolescents.",
        quality=0.96,
        authority_level=2,
        authority_score=0.93,
        verified=True,
        demo=False,
        provider="curated-pubmed",
        source_id="pubmed:42287698",
        independent_group="pubmed:42287698",
        trace_note="Curated PubMed meta-analysis published in 2026; reports an association and retains population and study-design limitations.",
    ),
    EvidenceRecord(
        id="pubmed-late-meal-systematic-review-28967343",
        keywords=("late eating", "evening intake", "dinner", "meal timing", "obesity", "BMI", "weight loss"),
        title="Are large dinners associated with excess weight, and does eating a smaller dinner achieve greater weight loss? A systematic review and meta-analysis",
        source="PubMed / British Journal of Nutrition",
        source_type="peer_reviewed",
        publication_date="2017-09-28",
        retrieved_at="2026-09-27",
        url="https://pubmed.ncbi.nlm.nih.gov/28967343/",
        canonical_url="https://pubmed.ncbi.nlm.nih.gov/28967343/",
        stance="neutral",
        excerpt="The systematic review found mixed observational results and a non-significant trend between evening intake and BMI; intervention trials did not show a significant difference in weight change, so recommendations to reduce evening intake for weight loss could not be substantiated by clinical evidence.",
        quality=0.94,
        authority_level=2,
        authority_score=0.91,
        verified=True,
        demo=False,
        provider="curated-pubmed",
        source_id="pubmed:28967343",
        independent_group="pubmed:28967343",
        trace_note="Curated PubMed systematic review used as limiting/neutral evidence to avoid overstating causality.",
    ),
    EvidenceRecord(
        id="pubmed-late-meal-obesity-37586316",
        keywords=("late eating", "last meal", "meal timing", "abdominal obesity", "obesity", "metabolic syndrome"),
        title="Late meal intake is associated with abdominal obesity and metabolic disorders related to metabolic syndrome: A chrononutrition approach using data from NHANES 2015-2018",
        source="PubMed / Clinical Nutrition",
        source_type="peer_reviewed",
        publication_date="2023-08-24",
        retrieved_at="2026-09-27",
        url="https://pubmed.ncbi.nlm.nih.gov/37586316/",
        canonical_url="https://pubmed.ncbi.nlm.nih.gov/37586316/",
        stance="support",
        excerpt="In a large US adult and older-adult population, a later last meal was associated with higher prevalence of abdominal obesity, while the study design supports association rather than a simple causal conclusion.",
        quality=0.92,
        authority_level=2,
        authority_score=0.90,
        verified=True,
        demo=False,
        provider="curated-pubmed",
        source_id="pubmed:37586316",
        independent_group="pubmed:37586316",
        trace_note="Curated PubMed observational study; interpreted as an association, not proof of causation.",
    ),
    EvidenceRecord(
        id="pubmed-sugar-ssb-diabetes-26199070",
        keywords=("sugar", "added sugar", "sugar-sweetened beverages", "sweet drinks", "diabetes", "type 2 diabetes", "T2D", "risk"),
        title="Consumption of sugar sweetened beverages, artificially sweetened beverages, and fruit juice and incidence of type 2 diabetes: systematic review, meta-analysis, and estimation of population attributable fraction",
        source="PubMed / BMJ",
        source_type="peer_reviewed",
        publication_date="2015-07-21",
        retrieved_at="2026-09-27",
        url="https://pubmed.ncbi.nlm.nih.gov/26199070/",
        canonical_url="https://pubmed.ncbi.nlm.nih.gov/26199070/",
        stance="support",
        excerpt="This systematic review and meta-analysis found that higher consumption of sugar-sweetened beverages was associated with greater incidence of type 2 diabetes, including after adjustment for adiposity.",
        quality=0.96,
        authority_level=2,
        authority_score=0.94,
        verified=True,
        demo=False,
        provider="curated-pubmed",
        source_id="pubmed:26199070",
        independent_group="pubmed:26199070",
        trace_note="Curated PubMed meta-analysis; observational evidence interpreted as an association, not proof of causation.",
    ),
    EvidenceRecord(
        id="pubmed-sugar-ssb-diabetes-24932880",
        keywords=("sugar", "sugar-sweetened beverages", "sweet drinks", "soft drinks", "diabetes", "type 2 diabetes", "risk", "BMI"),
        title="Association between sugar-sweetened and artificially sweetened soft drinks and type 2 diabetes: systematic review and dose-response meta-analysis of prospective studies",
        source="PubMed / British Journal of Nutrition",
        source_type="peer_reviewed",
        publication_date="2014-09-14",
        retrieved_at="2026-09-27",
        url="https://pubmed.ncbi.nlm.nih.gov/24932880/",
        canonical_url="https://pubmed.ncbi.nlm.nih.gov/24932880/",
        stance="support",
        excerpt="A systematic review and dose-response meta-analysis reported a positive association between sugar-sweetened soft drink intake and type 2 diabetes risk, with the association attenuated after adjustment for BMI.",
        quality=0.95,
        authority_level=2,
        authority_score=0.93,
        verified=True,
        demo=False,
        provider="curated-pubmed",
        source_id="pubmed:24932880",
        independent_group="pubmed:24932880",
        trace_note="Curated PubMed meta-analysis; reports an association and retains heterogeneity and observational limitations.",
    ),
    EvidenceRecord(
        id="pubmed-dietary-sugar-diabetes-40122386",
        keywords=("dietary sugar", "sugar", "sugar-sweetened beverages", "fruit juice", "added sugar", "diabetes", "type 2 diabetes", "T2D", "risk"),
        title="Dietary Sugar Intake and Incident Type 2 Diabetes Risk: A Systematic Review and Dose-Response Meta-Analysis of Prospective Cohort Studies",
        source="PubMed / Advances in Nutrition",
        source_type="peer_reviewed",
        publication_date="2025-03-19",
        retrieved_at="2026-09-27",
        url="https://pubmed.ncbi.nlm.nih.gov/40122386/",
        canonical_url="https://pubmed.ncbi.nlm.nih.gov/40122386/",
        stance="support",
        excerpt="A 2025 systematic review and dose-response meta-analysis found higher risk of type 2 diabetes with additional servings of sugar-sweetened beverages, while finding no association for added sugar as a category and noting that effects differ by sugar source.",
        quality=0.97,
        authority_level=2,
        authority_score=0.95,
        verified=True,
        demo=False,
        provider="curated-pubmed",
        source_id="pubmed:40122386",
        independent_group="pubmed:40122386",
        trace_note="Curated recent PubMed meta-analysis; reports an association for sugar-sweetened beverages and explicitly distinguishes beverage sugar from total/added sugar.",
    ),


    EvidenceRecord(
        id="pubmed-late-meal-gerd-rct-17573791",
        keywords=("late eating", "late meal timing", "dinner timing", "gastroesophageal reflux", "GERD", "acid reflux", "reflux symptoms", "heartburn"),
        title="Nocturnal reflux episodes following the administration of a standardized meal. Does timing matter?",
        source="PubMed / American Journal of Gastroenterology",
        source_type="peer_reviewed",
        publication_date="2007-10-01",
        retrieved_at="2026-09-27",
        url="https://pubmed.ncbi.nlm.nih.gov/17573791/",
        canonical_url="https://pubmed.ncbi.nlm.nih.gov/17573791/",
        stance="support",
        excerpt="In a randomized crossover trial of patients with reflux symptoms, a late evening meal produced significantly more supine reflux than an early meal. The study supports an association between late evening meals and nocturnal acid reflux in people with reflux symptoms.",
        quality=0.94,
        authority_level=2,
        authority_score=0.91,
        verified=True,
        demo=False,
        provider="curated-pubmed",
        source_id="pubmed:17573791",
        independent_group="pubmed:17573791",
        trace_note="Curated PubMed randomized crossover trial; reports an effect in people with reflux symptoms, but the population is limited and the finding is not proof of causation for everyone.",
    ),
    EvidenceRecord(
        id="pubmed-dinner-bed-gerd-16393212",
        keywords=("late eating", "dinner-to-bed time", "meal timing", "gastroesophageal reflux", "GERD", "acid reflux", "heartburn"),
        title="Association between dinner-to-bed time and gastro-esophageal reflux disease",
        source="PubMed / American Journal of Gastroenterology",
        source_type="peer_reviewed",
        publication_date="2005-12-01",
        retrieved_at="2026-09-27",
        url="https://pubmed.ncbi.nlm.nih.gov/16393212/",
        canonical_url="https://pubmed.ncbi.nlm.nih.gov/16393212/",
        stance="support",
        excerpt="A matched case-control study found that a shorter interval between dinner and bedtime was significantly associated with increased odds of gastro-esophageal reflux disease, particularly when dinner occurred less than three hours before sleep.",
        quality=0.93,
        authority_level=2,
        authority_score=0.90,
        verified=True,
        demo=False,
        provider="curated-pubmed",
        source_id="pubmed:16393212",
        independent_group="pubmed:16393212",
        trace_note="Curated PubMed case-control study; reports an association and should not be interpreted as proof that late eating alone causes GERD.",
    ),
    EvidenceRecord(
        id="acg-gerd-guideline-2022",
        keywords=("late eating", "late meal timing", "meals before bedtime", "gastroesophageal reflux", "GERD", "acid reflux", "reflux symptoms"),
        title="ACG Clinical Guideline: Guidelines for the Diagnosis and Management of Gastroesophageal Reflux Disease",
        source="American College of Gastroenterology",
        source_type="clinical_guideline",
        publication_date="2022-01-01",
        retrieved_at="2026-09-27",
        url="https://pmc.ncbi.nlm.nih.gov/articles/PMC8754510/",
        canonical_url="https://pmc.ncbi.nlm.nih.gov/articles/PMC8754510/",
        stance="support",
        excerpt="The guideline suggests avoiding meals within 2–3 hours of bedtime for patients with GERD symptoms and notes that a short interval between eating and bedtime is associated with increased GERD symptoms and medication need.",
        quality=0.97,
        authority_level=1,
        authority_score=0.95,
        verified=True,
        demo=False,
        provider="curated-guideline",
        source_id="acg-gerd-guideline-2022",
        independent_group="ACG",
        trace_note="Clinical guideline from the American College of Gastroenterology; recommendation is conditional and evidence quality is limited.",
    ),
    EvidenceRecord(
        id="niddk-gerd-eating-2020",
        keywords=("late eating", "meals before bedtime", "eat before bed", "gastroesophageal reflux", "GERD", "acid reflux", "reflux symptoms"),
        title="Eating, Diet, & Nutrition for GER & GERD",
        source="National Institute of Diabetes and Digestive and Kidney Diseases",
        source_type="government",
        publication_date="2020-07-01",
        retrieved_at="2026-09-27",
        url="https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults/eating-diet-nutrition",
        canonical_url="https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults/eating-diet-nutrition",
        stance="support",
        excerpt="NIDDK states that people with GERD symptoms at night or when lying down may benefit from meal timing that leaves at least three hours between eating and lying down or going to bed.",
        quality=0.96,
        authority_level=1,
        authority_score=0.98,
        verified=True,
        demo=False,
        provider="curated-government",
        source_id="niddk-gerd-eating-2020",
        independent_group="NIDDK",
        trace_note="US National Institutes of Health institute guidance; framed as symptom-management advice rather than proof of causation.",
    ),

    EvidenceRecord(
        id="nhs-cuts-grazes-wound-water-pus-2026",
        keywords=("luka", "wound", "water", "basah", "clean and dry", "pus", "nanah", "infection", "infeksi"),
        title="Cuts and grazes",
        source="NHS",
        source_type="government",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.nhs.uk/conditions/cuts-and-grazes/",
        canonical_url="https://www.nhs.uk/conditions/cuts-and-grazes/",
        stance="support",
        excerpt="NHS advises keeping a wound dressing clean and dry and keeping it away from water. It also lists pus coming from a cut as a sign that the wound may be infected and needs medical attention.",
        quality=0.96,
        authority_level=1,
        authority_score=0.98,
        verified=True,
        demo=False,
        provider="curated-government",
        source_id="nhs-cuts-grazes-wound-water-pus-2026",
        independent_group="NHS",
        trace_note="Official NHS wound-care guidance. It supports avoiding prolonged wetness and identifies pus as a sign of infection; it does not establish that every continuously wet wound will necessarily produce pus.",
    ),
    EvidenceRecord(
        id="medlineplus-surgical-wound-soaking-pus-2026",
        keywords=("luka", "wound", "soaking", "water", "basah", "infected", "infection", "pus", "nanah"),
        title="Surgical wound care - closed",
        source="MedlinePlus",
        source_type="government",
        publication_date="2026-04-11",
        retrieved_at="2026-09-27",
        url="https://medlineplus.gov/ency/patientinstructions/000738.htm",
        canonical_url="https://medlineplus.gov/ency/patientinstructions/000738.htm",
        stance="support",
        excerpt="MedlinePlus advises that soaking a surgical wound could cause it to reopen or become infected. It also says thick, tan, green, or yellow drainage, or bad-smelling drainage, may be pus and should prompt contact with the surgeon.",
        quality=0.97,
        authority_level=1,
        authority_score=0.98,
        verified=True,
        demo=False,
        provider="curated-government",
        source_id="medlineplus-surgical-wound-soaking-pus-2026",
        independent_group="MedlinePlus",
        trace_note="US National Library of Medicine patient guidance. It links soaking with infection risk and separately identifies pus-like drainage as a sign of infection; this is not proof that wetness alone always causes pus.",
    ),
    EvidenceRecord(
        id="southtees-lacerations-moisture-infection-2026",
        keywords=("luka", "wound", "moisture", "wet", "basah", "infection", "infeksi", "pus", "nanah"),
        title="Lacerations and incised wounds",
        source="South Tees Hospitals NHS Foundation Trust",
        source_type="government",
        publication_date="2022-01-01",
        retrieved_at="2026-09-27",
        url="https://www.southtees.nhs.uk/resources/lacerations-and-incised-wounds/",
        canonical_url="https://www.southtees.nhs.uk/resources/lacerations-and-incised-wounds/",
        stance="support",
        excerpt="South Tees Hospitals advises keeping wounds clean and dry and notes that excessive moisture may delay healing or introduce infection. It lists pus or blood-stained fluid as a sign of infection.",
        quality=0.95,
        authority_level=1,
        authority_score=0.96,
        verified=True,
        demo=False,
        provider="curated-government",
        source_id="southtees-lacerations-moisture-infection-2026",
        independent_group="South Tees Hospitals NHS Foundation Trust",
        trace_note="NHS hospital wound-care guidance. It supports a relationship between excessive moisture and infection risk and identifies pus as an infection sign, but does not establish a deterministic causal rule for every wound.",
    ),

    # Broad cancer-risk evidence pack. These records are intentionally claim-specific
    # so common cancer-risk questions do not depend on a single demo example.
    EvidenceRecord(
        id="who-cancer-risk-factors-2026",
        keywords=("kanker", "cancer", "rokok", "merokok", "tobacco", "alkohol", "alcohol", "obesitas", "berat badan", "aktivitas fisik", "olahraga", "polusi udara", "hpv", "hepatitis", "radiasi", "asbes", "aflatoksin", "diet", "makanan"),
        title="Cancer — risk factors and prevention",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-07-03",
        retrieved_at="2026-09-27",
        url="https://www.who.int/news-room/fact-sheets/detail/cancer",
        canonical_url="https://www.who.int/news-room/fact-sheets/detail/cancer",
        stance="support",
        excerpt="WHO menyebut penggunaan tembakau, konsumsi alkohol, pola makan tidak sehat, kurang aktivitas fisik, dan polusi udara sebagai faktor risiko kanker. WHO juga menjelaskan bahwa radiasi ultraviolet dan radiasi pengion merupakan karsinogen fisik, sedangkan asbes, komponen asap tembakau, alkohol, aflatoksin, dan arsenik merupakan karsinogen kimia.",
        quality=0.99,
        authority_level=1,
        authority_score=0.99,
        verified=True,
        demo=False,
        provider="curated-who",
        source_id="who-cancer-risk-factors-2026",
        independent_group="WHO",
        trace_note="WHO official cancer fact sheet; supports multiple established cancer risk-factor relationships without implying that every exposure guarantees cancer.",
    ),
    EvidenceRecord(
        id="who-alcohol-cancer-2025",
        keywords=("alkohol", "alcohol", "minuman beralkohol", "alcohol consumption", "kanker", "cancer", "kanker payudara", "breast cancer", "kanker hati", "liver cancer", "kanker kolorektal", "colorectal cancer", "kanker esofagus", "oesophageal cancer"),
        title="Alcohol and cancer",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2025-11-26",
        retrieved_at="2026-09-27",
        url="https://www.who.int/europe/news-room/fact-sheets/item/alcohol-and-cancer",
        canonical_url="https://www.who.int/europe/news-room/fact-sheets/item/alcohol-and-cancer",
        stance="support",
        excerpt="WHO menyatakan alkohol merupakan karsinogen dan konsumsi alkohol meningkatkan risiko beberapa kanker, termasuk kanker payudara, hati, kepala dan leher, esofagus, dan kolorektal.",
        quality=0.98,
        authority_level=1,
        authority_score=0.98,
        verified=True,
        demo=False,
        provider="curated-who",
        source_id="who-alcohol-cancer-2025",
        independent_group="WHO",
        trace_note="WHO Europe official fact sheet directly linking alcohol consumption with several cancers.",
    ),
    EvidenceRecord(
        id="iarc-obesity-cancer-2026",
        keywords=("obesitas", "obesity", "berat badan", "overweight", "kelebihan berat badan", "bmi", "kanker", "cancer", "kanker payudara", "breast cancer", "kanker usus besar", "colon cancer", "kanker endometrium", "endometrial cancer"),
        title="Obesity as an Avoidable Cause of Cancer",
        source="International Agency for Research on Cancer",
        source_type="international_health_agency",
        publication_date="2026-09-27",
        retrieved_at="2026-09-27",
        url="https://www.iarc.who.int/reference/obesity-as-an-avoidable-cause-of-cancer-attributable-risks/",
        canonical_url="https://www.iarc.who.int/reference/obesity-as-an-avoidable-cause-of-cancer-attributable-risks/",
        stance="support",
        excerpt="IARC menyatakan kelebihan berat badan dan obesitas merupakan faktor risiko yang telah ditetapkan untuk peningkatan kejadian beberapa kanker pada orang dewasa, termasuk kanker endometrium, payudara pascamenopause, dan kolon.",
        quality=0.98,
        authority_level=1,
        authority_score=0.98,
        verified=True,
        demo=False,
        provider="curated-iarc",
        source_id="iarc-obesity-cancer-2026",
        independent_group="IARC",
        trace_note="IARC reference page directly linking excess body weight with several adult cancers.",
    ),
    EvidenceRecord(
        id="who-uv-skin-cancer-2022",
        keywords=("sinar uv", "uv", "ultraviolet", "radiasi ultraviolet", "paparan matahari", "sinar matahari", "sunburn", "tanning", "kanker kulit", "skin cancer", "melanoma", "melanoma", "kanker", "cancer"),
        title="Ultraviolet radiation",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2022-06-21",
        retrieved_at="2026-09-27",
        url="https://www.who.int/news-room/fact-sheets/detail/ultraviolet-radiation",
        canonical_url="https://www.who.int/news-room/fact-sheets/detail/ultraviolet-radiation",
        stance="support",
        excerpt="WHO menyatakan kanker kulit terutama disebabkan oleh paparan radiasi ultraviolet dari matahari atau sumber buatan seperti sunbeds. Paparan UV berlebihan bersifat karsinogenik dan berhubungan dengan melanoma serta kanker kulit non-melanoma.",
        quality=0.99,
        authority_level=1,
        authority_score=0.99,
        verified=True,
        demo=False,
        provider="curated-who",
        source_id="who-uv-skin-cancer-2022",
        independent_group="WHO",
        trace_note="WHO official UV radiation fact sheet directly linking excessive UV exposure with skin cancer.",
    ),
    EvidenceRecord(
        id="who-air-pollution-lung-cancer-2026",
        keywords=("polusi udara", "air pollution", "pencemaran udara", "particulate matter", "pm2.5", "asap kendaraan", "diesel exhaust", "kanker paru", "lung cancer", "kanker", "cancer"),
        title="Cancer — air pollution as a risk factor",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-07-03",
        retrieved_at="2026-09-27",
        url="https://www.who.int/news-room/fact-sheets/detail/cancer",
        canonical_url="https://www.who.int/news-room/fact-sheets/detail/cancer",
        stance="support",
        excerpt="WHO menyebut polusi udara sebagai faktor risiko penting untuk kanker paru. Paparan polusi udara luar dan dalam ruangan termasuk faktor lingkungan yang dapat meningkatkan beban penyakit kanker.",
        quality=0.98,
        authority_level=1,
        authority_score=0.98,
        verified=True,
        demo=False,
        provider="curated-who",
        source_id="who-air-pollution-lung-cancer-2026",
        independent_group="WHO",
        trace_note="WHO official cancer fact sheet directly identifies air pollution as an important lung-cancer risk factor.",
    ),
    EvidenceRecord(
        id="who-infections-cancer-2026",
        keywords=("hpv", "human papillomavirus", "hepatitis b", "hepatitis c", "hbv", "hcv", "epstein-barr", "ebv", "h pylori", "helicobacter pylori", "infeksi", "infection", "kanker", "cancer", "kanker serviks", "cervical cancer", "kanker hati", "liver cancer"),
        title="Cancer — carcinogenic infections",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-07-03",
        retrieved_at="2026-09-27",
        url="https://www.who.int/news-room/fact-sheets/detail/cancer",
        canonical_url="https://www.who.int/news-room/fact-sheets/detail/cancer",
        stance="support",
        excerpt="WHO menjelaskan bahwa infeksi kronis tertentu merupakan faktor risiko kanker. HPV meningkatkan risiko kanker serviks, sedangkan hepatitis B dan C meningkatkan risiko kanker hati; Helicobacter pylori dan Epstein-Barr virus juga termasuk infeksi karsinogenik.",
        quality=0.99,
        authority_level=1,
        authority_score=0.99,
        verified=True,
        demo=False,
        provider="curated-who",
        source_id="who-infections-cancer-2026",
        independent_group="WHO",
        trace_note="WHO official cancer fact sheet directly linking several carcinogenic infections to cancer risk.",
    ),
    EvidenceRecord(
        id="who-occupational-carcinogens-2026",
        keywords=("asbes", "asbestos", "paparan kerja", "occupational exposure", "occupational carcinogen", "benzena", "benzene", "arsenik", "arsenic", "silika", "silica", "kromium", "chromium", "nikel", "nickel", "radon", "kanker paru", "lung cancer", "mesothelioma", "kanker kandung kemih", "bladder cancer", "kanker", "cancer"),
        title="Preventing cancer — occupational carcinogens",
        source="World Health Organization",
        source_type="international_health_agency",
        publication_date="2026-01-01",
        retrieved_at="2026-09-27",
        url="https://www.who.int/activities/preventing-cancer/preventing-cancer",
        canonical_url="https://www.who.int/activities/preventing-cancer/preventing-cancer",
        stance="support",
        excerpt="WHO menjelaskan bahwa karsinogen di tempat kerja berhubungan secara kausal dengan kanker paru, mesothelioma, dan kanker kandung kemih. Paparan asbes di tempat kerja merupakan penyebab utama mesothelioma.",
        quality=0.98,
        authority_level=1,
        authority_score=0.98,
        verified=True,
        demo=False,
        provider="curated-who",
        source_id="who-occupational-carcinogens-2026",
        independent_group="WHO",
        trace_note="WHO cancer prevention page directly covers occupational carcinogens and asbestos-related cancer.",
    ),
    EvidenceRecord(
        id="iarc-preventable-cancer-causes-2026",
        keywords=("rokok", "merokok", "tobacco", "alkohol", "alcohol", "obesitas", "berat badan", "infeksi", "infection", "sinar uv", "ultraviolet", "kanker", "cancer", "polusi udara", "aktivitas fisik"),
        title="Four in ten cancer cases could be prevented globally",
        source="International Agency for Research on Cancer",
        source_type="international_health_agency",
        publication_date="2026-02-03",
        retrieved_at="2026-09-27",
        url="https://www.iarc.who.int/news-events/four-in-ten-cancer-cases-could-be-prevented-globally/",
        canonical_url="https://www.iarc.who.int/news-events/four-in-ten-cancer-cases-could-be-prevented-globally/",
        stance="support",
        excerpt="Analisis WHO dan IARC tahun 2026 mencakup 30 penyebab yang dapat dicegah, termasuk tembakau, alkohol, indeks massa tubuh tinggi, kurang aktivitas fisik, polusi udara, radiasi ultraviolet, dan infeksi penyebab kanker.",
        quality=0.98,
        authority_level=1,
        authority_score=0.98,
        verified=True,
        demo=False,
        provider="curated-iarc",
        source_id="iarc-preventable-cancer-causes-2026",
        independent_group="IARC",
        trace_note="IARC 2026 global analysis covering multiple preventable cancer causes across 185 countries and 36 cancer types.",
    ),
]


class DemoEvidenceProvider:
    @property
    def is_demo(self) -> bool:
        return all(record.demo for record in _RECORDS)

    def records(self) -> list[EvidenceRecord]:
        # Keep one canonical record per URL. Earlier fallback expansions added
        # a few source snapshots twice under different IDs, which inflated
        # source counts and violated the independent-source contract.
        records: list[EvidenceRecord] = []
        seen_urls: set[str] = set()
        for record in [*_RECORDS, *COMMON_HEALTH_RECORDS]:
            url = (record.canonical_url or record.url).rstrip("/").lower()
            if url in seen_urls:
                continue
            seen_urls.add(url)
            records.append(record)
        return records
